name              'base'
description       'Deploys and configures base recipes'
long_description  '# base chef cookbook\n\nDeploys and configures base recipes\n'
maintainer_email  'neillwturner@gmail.com'
license           'Apache 2.0'
version           '1.0.0'
supports          'debian', '>= 0.0.0'
supports          'ubuntu', '>= 0.0.0'
depends           'aws', '>= 0.0.0'